version: '2'
services:

  database:
    container_name: desafio-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=desafio
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data
    ports:
      - "5434:5432"